In [ ]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index=range(1,51))
scores_pd

In [ ]:
scores_pd.index.name='學號'
scores_pd.columns.name='科目'
scores_pd

In [11]:
display(scores_pd['國文'][:10])
scores_pd['數學'][:10]

學號
1     60
2     72
3     76
4     91
5     89
6     96
7     50
8     97
9     98
10    94
Name: 國文, dtype: int64

學號
1     67
2     69
3     62
4     95
5     78
6     53
7     74
8     89
9     83
10    57
Name: 數學, dtype: int64

In [12]:
scores_pd['國文'][:10] + scores_pd['數學'][:10]

學號
1     127
2     141
3     138
4     186
5     167
6     149
7     124
8     186
9     181
10    151
dtype: int64

In [13]:
scores_pd['國文'] + scores_pd['英文'] +scores_pd['地理'] + scores_pd['歷史'] + scores_pd['數學']

學號
1     362
2     362
3     326
4     412
5     410
6     371
7     342
8     407
9     387
10    383
11    364
12    380
13    367
14    370
15    386
16    340
17    372
18    343
19    405
20    324
21    431
22    348
23    400
24    350
25    325
26    380
27    325
28    376
29    323
30    407
31    390
32    404
33    374
34    389
35    380
36    415
37    366
38    367
39    357
40    369
41    403
42    366
43    384
44    404
45    363
46    400
47    346
48    360
49    408
50    371
dtype: int64

In [ ]:
scores_pd['總分'] =scores_pd.sum(axis=1)
scores_pd['平均'] = scores_pd[['國文','英文','數學','地理','歷史']].mean(axis=1)
scores_pd

In [21]:
scores_pd['排名'] =scores_pd['總分'].rank(method=',min',ascending=False)
scores_pd

KeyError: ',min'

In [28]:
scores_pd.sort_values(by='排名')

科目  國文   英文  數學   地理  歷史   總分    平均    排名
學號
21  73   98  83   81  96  862  86.2   1.0
36  91   84  78   83  79  830  83.0   2.0
4   91   90  95   68  68  824  82.4   3.0
5   89   67  78   84  92  820  82.0   4.0
49  94   69  88   75  82  816  81.6   5.0
8   97  100  89   69  52  814  81.4   6.0
30  64  100  94   54  95  814  81.4   7.0
19  97   84  79   78  67  810  81.0   8.0
32  71   92  88   94  59  808  80.8   9.0
44  88   52  95   75  94  808  80.8  10.0
41  94   74  98   64  73  806  80.6  11.0
23  67   95  85   94  59  800  80.0  12.0
46  73   97  80   54  96  800  80.0  13.0
31  77   90  66   81  76  780  78.0  14.0
34  79   52  84   78  96  778  77.8  15.0
9   98   59  83   71  76  774  77.4  16.0
15  54   84  94   72  82  772  77.2  17.0
43  72   54  71   98  89  768  76.8  18.0
10  94   88  57   60  84  766  76.6  19.0
12  65   76  84  100  55  760  76.0  20.0
26  93   58  92   66  71  760  76.0  21.0
35  56   97  82   84  61  760  76.0  22.0
28  89   64  92   79  52  752  75.2  23.0
33  50   94  58   85  87  748  74.8  24.0
17  57   97  67   67  84  744  74.4  25.0
6   96   65  53   90  67  742  74.2  26.0
50  92   57  77   89  56  742  74.2  27.0
14  75   72  81   65  77  740  74.0  28.0
40  66   71  73   81  78  738  73.8  29.0
13  80   73  62   85  67  734  73.4  30.0
38  79   55  89   50  94  734  73.4  31.0
37  92   63  59   58  94  732  73.2  32.0
42  70   51  86   84  75  732  73.2  33.0
11  88   62  51   79  84  728  72.8  34.0
45  53   78  85   72  75  726  72.6  35.0
1   60   53  67   95  87  724  72.4  36.0
2   72   70  69   71  80  724  72.4  37.0
48  73   66  70   80  71  720  72.0  38.0
39  77   80  50   59  91  714  71.4  39.0
24  77   96  67   54  56  700  70.0  40.0
22  78   57  59  100  54  696  69.6  41.0
47  87   54  63   91  51  692  69.2  42.0
18  73   65  52   96  57  686  68.6  43.0
7   50   82  74   59  77  684  68.4  44.0
16  76   59  53   85  67  680  68.0  45.0
3   76   58  62   71  59  652  65.2  46.0
25  78   57  51   83  56  650  65.0  47.0
27  66   73  60   63  63  650  65.0  48.0
20  59   52  56   58  99  648  64.8  49.0
29  51   52  86   66  68  646  64.6  50.0

In [ ]:
def format60(v:int):
    if v >=60:
        return'及格'
    else:
        return'不及格'
    
scores_pd[['國文','英文','數學','地理','歷史']].style.format(format60)

In [34]:
scores_pd.style\
.highlight_between(left=0,
                   right=59,
                   color='red',
                   subset=['國文','英文','數學','地理','歷史'],
                   props='color:white;background-color:red')\
.format(precision=0,subset=['平均','排名']).to_excel('scores.xlsx')

In [41]:
def callback1(value:pd.Series):
    return pd.Series ([value.max(),value.min(),value.median(),value.mean()],index=['最高分','最低分','中間值','平均值'])

dataFrame1 = scores_pd.apply(callback1)
dataFrame1

科目      國文      英文    數學      地理     歷史      總分      平均    排名
最高分  98.00  100.00  98.0  100.00  99.00  862.00  86.200  50.0
最低分  50.00   51.00  50.0   50.00  51.00  646.00  64.600   1.0
中間值  76.50   70.50  77.5   78.00  75.50  743.00  74.300  25.5
平均值  76.34   72.72  74.3   75.96  74.56  747.76  74.776  25.5